name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true
      - run: make hexlet-path-size
      - uses: actions/upload-artifact@v4
        with:
          name: hexlet-path-size
          path: bin/hexlet-path-size

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m